disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Alex's Homepage"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

 [params.author]
   name = "Alex Lozko"
   email = "alexlozkoIT@gmail.com"
   image = "img/alex.jpg"
   # image = "img/blowfish_logo.png"
   imageQuality = 96
   headline = "QA | Test Automation | SDET | DevOps"
   bio = "QA | Test Automation | SDET | DevOps"
   links = [
     { email = "mailto:alexlozkoIT@gmail.com" },
     { link = "https://alexlozko.com/" },
     { github = "https://github.com/lozal" },
     { linkedin = "https://www.linkedin.com/in/alexanderlozko/" }
   ]
